# Generated by Django 2.2 on 2019-04-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20190417_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('contact_info', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
