# Generated by Django 2.2 on 2019-04-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20190417_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_us',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
