# Generated by Django 2.2 on 2019-04-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20190417_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pay_through',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
