# Generated by Django 2.2 on 2019-04-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_auto_20190418_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
